interfaces:
  interfaces.IPayment:
    - services.payment.CashPayment
    - services.payment.MelatGateway
  interfaces.IShipping:
    - services.shipping.PishtazShipping
    - services.shipping.AloPeikShipping
  interfaces.IAwardPolicy:
    - services.award.AwardByCount
mappers:
  models.User: persistance.mappers.FileMapper
  models.Product: persistance.mappers.FileMapper
  models.Basket: persistance.mappers.FileMapper
  models.Shipping: persistance.mappers.FileMapper
  models.Payment: persistance.mappers.FileMapper

credentials:
  services.payment.MelatGateway:
    token: "akhdcs55232rfc"
  services.external.Post:
    username: "Store"
    password: "csf41f5556fv1"
